### ISSUE TITLE
Example of wrong ClinVar disease association

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#204] opened 2019-09-11 01:12 UTC
Angelman syndrome (https://omim.org/entry/105830?search=angelman&highlight=angelman) is not caused by MECP2 mutations (https://beta.monarchinitiative.org/disease/OMIM:105830#gene)
It is unreliable to extract gene<->disease associations from ClinVar
If you follow this, it relates to this 2001 publication, https://www.ncbi.nlm.nih.gov/pubmed/11283202,
This does not reflect current knowledge anymore, MECp2 is not mentioned on the OMIM page at all for instance.

**Comment by monicacecilia** [comment] 2019-09-11 08:38
dupe of #139 - closing in favour of the discussion going on there. AND adding this example to that ticket.

**Closed by monicacecilia** 2019-09-11 08:38 UTC
