### ISSUE TITLE
Add some kind of filters to large phenotype pages

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#329] opened 2020-05-11 19:16 UTC
Pages like https://monarchinitiative.org/gene/ZFIN:ZDB-GENE-980526-166#phenotype are hard to look through; it would be good if there was some way to drill down into the data ala ribbons, phenogrid, or simply filters on table columns; especially if you wanna get a sense like: what kind of phenotypes is this gene involved in?

**Comment by kshefchek** [comment] 2020-05-12 23:05
Dupe of https://github.com/monarch-initiative/monarch-ui/issues/318, will add your comments there

**Closed** 2020-12-08 21:05 UTC
