### ISSUE TITLE
Phenomics Page

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#359] opened 2020-08-11 17:01 UTC
We need to repurpose the existing /about/phenotypes for phenomics first.
We should perhaps think about whether we want to rename it /about/phenomics? @mellybelly 

The page should be an overview of phenomics with the following sections
- About phenotypes
  - What is a phenotype
  - What is a phenotype profile
  - What is phenomics

- Our phenomics toolkit
  - HPO
  - Mondo
  - uPheno
  - Phenopackets
  - Exomiser
  - APIs

Phenomics Workshops (link to the gh .io page)

How we dovetail this with the GCE is not clear to me yet

**Comment by nlharris** [comment] 2023-03-29 20:57
@monicacecilia wrote (in email):
> I believe there is already a stub Nico and I created a few months back and lived in a branch on the (now 'old' UI?) website repo. We should update it and push it.

**Comment by sagehrke** [comment] 2023-07-18 20:20
Dupe of https://github.com/monarch-initiative/monarch-app/issues/210

**Comment by sagehrke** [comment] 2023-09-05 20:58
Completed with https://github.com/monarch-initiative/monarch-app/issues/210

**Closed by sagehrke** 2023-09-05 20:58 UTC
