### ISSUE TITLE
Add and update pages on: publications, link to us

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#107] opened 2019-07-02 19:06 UTC
- [x] publications
- [x] link to us
- [-] ~~services~~ see #152
- [-] ~~releases~~ see #58
- [-] ~~data sources~~ see #58 

Legacy pages:
https://monarchinitiative.org/page/pubs
https://monarchinitiative.org/about/sources
https://monarchinitiative.org/page/services
https://monarchinitiative.org/page/links
https://monarchinitiative.org/page/releases

Some potential overlap with https://github.com/monarch-initiative/monarch-ui/issues/58

**Comment by monicacecilia** [comment] 2019-07-09 02:48
Dupe of #65

**Comment by monicacecilia** [comment] 2019-07-09 17:10
For _Publications_ page: add PubMan tool https://github.com/monarch-initiative/pubman
Request to also add hyperlinks to the publications, possibly via PubMed ID

**Comment by pnrobinson** [comment] 2019-07-09 20:37
@monicacecilia @cmungall  I need to know where to put the new Services page. The new menu structure does not have the same structure as the old one. I am assuming this is intentional and so I will put it under about. If this is not what we want please shout soon

**Comment by pnrobinson** [comment] 2019-07-10 11:12
@cmungall @monicacecilia @jmcmurry The current webservices page was made without a lot of love: https://monarchinitiative.org/page/services
There is no sense of putting stuff like this on our webpage since it is uninformative to new users. Can you please provide some texts for
1. What is Biolink API? What are the things it can do? Who is it intended for?
2. The links to the biolink and SciGraph APIs are to pages that look roughly the same at first glance. However, the style is different. Why is that? Also, when should a user want to use scigraph and when should then want to user biolink. 
3. The figure is out of date. It also contains elements that are still current such as owlsim but that are not explained on the page. 

I am going to mark this issue as blocked, please let me know when we have new texts etc!

**Comment by monicacecilia** [comment] 2019-07-12 18:17
@pnrobinson, regarding the 'Services' page, I made a suggestion in #128 to replace (at least for now) https://monarchinitiative.org/page/services with the page at https://api.monarchinitiative.org/api/

**Comment by monicacecilia** [comment] 2019-08-02 18:52
- Work on ___Link to Monarch___ and ___Publications___ has now been completed by @iimpulse & @pnrobinson. Thanks!
- A new ___Services___ page has been requested with specifications at #152.  
- Progress on ___Releases___ and ___Data Sources___ can be followed in #58. 

Closing this issue in favour of those two. :bowtie:

**Closed by monicacecilia** 2019-08-02 18:52 UTC
Labels: blocked by lack of documemtation
