### ISSUE TITLE
Fix list of collaborators and grant info on homepage

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#103] opened 2019-07-01 21:27 UTC
For collabs:
- Remove Garvan and add Jax

For grants:
I'm unsure which are outdated or missing, @jmcmurry @monicacecilia could you help here?

**Comment by monicacecilia** [comment] 2019-07-01 23:24
Dupe of #65. I'll add this information there.

**Closed by monicacecilia** 2019-07-01 23:24 UTC
